// Code generated by SQLBoiler 4.10.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// LinkTransitiveClosure is an object representing the database table.
type LinkTransitiveClosure struct {
	ID       int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	ParentID string `boil:"parent_id" json:"parent_id" toml:"parent_id" yaml:"parent_id"`
	ChildID  string `boil:"child_id" json:"child_id" toml:"child_id" yaml:"child_id"`

	R *linkTransitiveClosureR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L linkTransitiveClosureL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var LinkTransitiveClosureColumns = struct {
	ID       string
	ParentID string
	ChildID  string
}{
	ID:       "id",
	ParentID: "parent_id",
	ChildID:  "child_id",
}

var LinkTransitiveClosureTableColumns = struct {
	ID       string
	ParentID string
	ChildID  string
}{
	ID:       "link_transitive_closure.id",
	ParentID: "link_transitive_closure.parent_id",
	ChildID:  "link_transitive_closure.child_id",
}

// Generated where

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var LinkTransitiveClosureWhere = struct {
	ID       whereHelperint
	ParentID whereHelperstring
	ChildID  whereHelperstring
}{
	ID:       whereHelperint{field: "\"link_transitive_closure\".\"id\""},
	ParentID: whereHelperstring{field: "\"link_transitive_closure\".\"parent_id\""},
	ChildID:  whereHelperstring{field: "\"link_transitive_closure\".\"child_id\""},
}

// LinkTransitiveClosureRels is where relationship names are stored.
var LinkTransitiveClosureRels = struct {
	Child  string
	Parent string
}{
	Child:  "Child",
	Parent: "Parent",
}

// linkTransitiveClosureR is where relationships are stored.
type linkTransitiveClosureR struct {
	Child  *Link  `boil:"Child" json:"Child" toml:"Child" yaml:"Child"`
	Parent *Topic `boil:"Parent" json:"Parent" toml:"Parent" yaml:"Parent"`
}

// NewStruct creates a new relationship struct
func (*linkTransitiveClosureR) NewStruct() *linkTransitiveClosureR {
	return &linkTransitiveClosureR{}
}

// linkTransitiveClosureL is where Load methods for each relationship are stored.
type linkTransitiveClosureL struct{}

var (
	linkTransitiveClosureAllColumns            = []string{"id", "parent_id", "child_id"}
	linkTransitiveClosureColumnsWithoutDefault = []string{"parent_id", "child_id"}
	linkTransitiveClosureColumnsWithDefault    = []string{"id"}
	linkTransitiveClosurePrimaryKeyColumns     = []string{"id"}
	linkTransitiveClosureGeneratedColumns      = []string{}
)

type (
	// LinkTransitiveClosureSlice is an alias for a slice of pointers to LinkTransitiveClosure.
	// This should almost always be used instead of []LinkTransitiveClosure.
	LinkTransitiveClosureSlice []*LinkTransitiveClosure

	linkTransitiveClosureQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	linkTransitiveClosureType                 = reflect.TypeOf(&LinkTransitiveClosure{})
	linkTransitiveClosureMapping              = queries.MakeStructMapping(linkTransitiveClosureType)
	linkTransitiveClosurePrimaryKeyMapping, _ = queries.BindMapping(linkTransitiveClosureType, linkTransitiveClosureMapping, linkTransitiveClosurePrimaryKeyColumns)
	linkTransitiveClosureInsertCacheMut       sync.RWMutex
	linkTransitiveClosureInsertCache          = make(map[string]insertCache)
	linkTransitiveClosureUpdateCacheMut       sync.RWMutex
	linkTransitiveClosureUpdateCache          = make(map[string]updateCache)
	linkTransitiveClosureUpsertCacheMut       sync.RWMutex
	linkTransitiveClosureUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single linkTransitiveClosure record from the query.
func (q linkTransitiveClosureQuery) One(ctx context.Context, exec boil.ContextExecutor) (*LinkTransitiveClosure, error) {
	o := &LinkTransitiveClosure{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for link_transitive_closure")
	}

	return o, nil
}

// All returns all LinkTransitiveClosure records from the query.
func (q linkTransitiveClosureQuery) All(ctx context.Context, exec boil.ContextExecutor) (LinkTransitiveClosureSlice, error) {
	var o []*LinkTransitiveClosure

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to LinkTransitiveClosure slice")
	}

	return o, nil
}

// Count returns the count of all LinkTransitiveClosure records in the query.
func (q linkTransitiveClosureQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count link_transitive_closure rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q linkTransitiveClosureQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if link_transitive_closure exists")
	}

	return count > 0, nil
}

// Child pointed to by the foreign key.
func (o *LinkTransitiveClosure) Child(mods ...qm.QueryMod) linkQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ChildID),
	}

	queryMods = append(queryMods, mods...)

	return Links(queryMods...)
}

// Parent pointed to by the foreign key.
func (o *LinkTransitiveClosure) Parent(mods ...qm.QueryMod) topicQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ParentID),
	}

	queryMods = append(queryMods, mods...)

	return Topics(queryMods...)
}

// LoadChild allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (linkTransitiveClosureL) LoadChild(ctx context.Context, e boil.ContextExecutor, singular bool, maybeLinkTransitiveClosure interface{}, mods queries.Applicator) error {
	var slice []*LinkTransitiveClosure
	var object *LinkTransitiveClosure

	if singular {
		object = maybeLinkTransitiveClosure.(*LinkTransitiveClosure)
	} else {
		slice = *maybeLinkTransitiveClosure.(*[]*LinkTransitiveClosure)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &linkTransitiveClosureR{}
		}
		args = append(args, object.ChildID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &linkTransitiveClosureR{}
			}

			for _, a := range args {
				if a == obj.ChildID {
					continue Outer
				}
			}

			args = append(args, obj.ChildID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`links`),
		qm.WhereIn(`links.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Link")
	}

	var resultSlice []*Link
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Link")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for links")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for links")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Child = foreign
		if foreign.R == nil {
			foreign.R = &linkR{}
		}
		foreign.R.ChildLinkTransitiveClosures = append(foreign.R.ChildLinkTransitiveClosures, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ChildID == foreign.ID {
				local.R.Child = foreign
				if foreign.R == nil {
					foreign.R = &linkR{}
				}
				foreign.R.ChildLinkTransitiveClosures = append(foreign.R.ChildLinkTransitiveClosures, local)
				break
			}
		}
	}

	return nil
}

// LoadParent allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (linkTransitiveClosureL) LoadParent(ctx context.Context, e boil.ContextExecutor, singular bool, maybeLinkTransitiveClosure interface{}, mods queries.Applicator) error {
	var slice []*LinkTransitiveClosure
	var object *LinkTransitiveClosure

	if singular {
		object = maybeLinkTransitiveClosure.(*LinkTransitiveClosure)
	} else {
		slice = *maybeLinkTransitiveClosure.(*[]*LinkTransitiveClosure)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &linkTransitiveClosureR{}
		}
		args = append(args, object.ParentID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &linkTransitiveClosureR{}
			}

			for _, a := range args {
				if a == obj.ParentID {
					continue Outer
				}
			}

			args = append(args, obj.ParentID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`topics`),
		qm.WhereIn(`topics.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Topic")
	}

	var resultSlice []*Topic
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Topic")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for topics")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for topics")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Parent = foreign
		if foreign.R == nil {
			foreign.R = &topicR{}
		}
		foreign.R.ParentLinkTransitiveClosures = append(foreign.R.ParentLinkTransitiveClosures, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ParentID == foreign.ID {
				local.R.Parent = foreign
				if foreign.R == nil {
					foreign.R = &topicR{}
				}
				foreign.R.ParentLinkTransitiveClosures = append(foreign.R.ParentLinkTransitiveClosures, local)
				break
			}
		}
	}

	return nil
}

// SetChild of the linkTransitiveClosure to the related item.
// Sets o.R.Child to related.
// Adds o to related.R.ChildLinkTransitiveClosures.
func (o *LinkTransitiveClosure) SetChild(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Link) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"link_transitive_closure\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"child_id"}),
		strmangle.WhereClause("\"", "\"", 2, linkTransitiveClosurePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ChildID = related.ID
	if o.R == nil {
		o.R = &linkTransitiveClosureR{
			Child: related,
		}
	} else {
		o.R.Child = related
	}

	if related.R == nil {
		related.R = &linkR{
			ChildLinkTransitiveClosures: LinkTransitiveClosureSlice{o},
		}
	} else {
		related.R.ChildLinkTransitiveClosures = append(related.R.ChildLinkTransitiveClosures, o)
	}

	return nil
}

// SetParent of the linkTransitiveClosure to the related item.
// Sets o.R.Parent to related.
// Adds o to related.R.ParentLinkTransitiveClosures.
func (o *LinkTransitiveClosure) SetParent(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Topic) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"link_transitive_closure\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"parent_id"}),
		strmangle.WhereClause("\"", "\"", 2, linkTransitiveClosurePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ParentID = related.ID
	if o.R == nil {
		o.R = &linkTransitiveClosureR{
			Parent: related,
		}
	} else {
		o.R.Parent = related
	}

	if related.R == nil {
		related.R = &topicR{
			ParentLinkTransitiveClosures: LinkTransitiveClosureSlice{o},
		}
	} else {
		related.R.ParentLinkTransitiveClosures = append(related.R.ParentLinkTransitiveClosures, o)
	}

	return nil
}

// LinkTransitiveClosures retrieves all the records using an executor.
func LinkTransitiveClosures(mods ...qm.QueryMod) linkTransitiveClosureQuery {
	mods = append(mods, qm.From("\"link_transitive_closure\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"link_transitive_closure\".*"})
	}

	return linkTransitiveClosureQuery{q}
}

// FindLinkTransitiveClosure retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLinkTransitiveClosure(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*LinkTransitiveClosure, error) {
	linkTransitiveClosureObj := &LinkTransitiveClosure{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"link_transitive_closure\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, linkTransitiveClosureObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from link_transitive_closure")
	}

	return linkTransitiveClosureObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *LinkTransitiveClosure) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no link_transitive_closure provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(linkTransitiveClosureColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	linkTransitiveClosureInsertCacheMut.RLock()
	cache, cached := linkTransitiveClosureInsertCache[key]
	linkTransitiveClosureInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			linkTransitiveClosureAllColumns,
			linkTransitiveClosureColumnsWithDefault,
			linkTransitiveClosureColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(linkTransitiveClosureType, linkTransitiveClosureMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(linkTransitiveClosureType, linkTransitiveClosureMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"link_transitive_closure\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"link_transitive_closure\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into link_transitive_closure")
	}

	if !cached {
		linkTransitiveClosureInsertCacheMut.Lock()
		linkTransitiveClosureInsertCache[key] = cache
		linkTransitiveClosureInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the LinkTransitiveClosure.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *LinkTransitiveClosure) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	linkTransitiveClosureUpdateCacheMut.RLock()
	cache, cached := linkTransitiveClosureUpdateCache[key]
	linkTransitiveClosureUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			linkTransitiveClosureAllColumns,
			linkTransitiveClosurePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update link_transitive_closure, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"link_transitive_closure\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, linkTransitiveClosurePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(linkTransitiveClosureType, linkTransitiveClosureMapping, append(wl, linkTransitiveClosurePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update link_transitive_closure row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for link_transitive_closure")
	}

	if !cached {
		linkTransitiveClosureUpdateCacheMut.Lock()
		linkTransitiveClosureUpdateCache[key] = cache
		linkTransitiveClosureUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q linkTransitiveClosureQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for link_transitive_closure")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for link_transitive_closure")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LinkTransitiveClosureSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), linkTransitiveClosurePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"link_transitive_closure\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, linkTransitiveClosurePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in linkTransitiveClosure slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all linkTransitiveClosure")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *LinkTransitiveClosure) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no link_transitive_closure provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(linkTransitiveClosureColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	linkTransitiveClosureUpsertCacheMut.RLock()
	cache, cached := linkTransitiveClosureUpsertCache[key]
	linkTransitiveClosureUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			linkTransitiveClosureAllColumns,
			linkTransitiveClosureColumnsWithDefault,
			linkTransitiveClosureColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			linkTransitiveClosureAllColumns,
			linkTransitiveClosurePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert link_transitive_closure, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(linkTransitiveClosurePrimaryKeyColumns))
			copy(conflict, linkTransitiveClosurePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"link_transitive_closure\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(linkTransitiveClosureType, linkTransitiveClosureMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(linkTransitiveClosureType, linkTransitiveClosureMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert link_transitive_closure")
	}

	if !cached {
		linkTransitiveClosureUpsertCacheMut.Lock()
		linkTransitiveClosureUpsertCache[key] = cache
		linkTransitiveClosureUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single LinkTransitiveClosure record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *LinkTransitiveClosure) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no LinkTransitiveClosure provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), linkTransitiveClosurePrimaryKeyMapping)
	sql := "DELETE FROM \"link_transitive_closure\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from link_transitive_closure")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for link_transitive_closure")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q linkTransitiveClosureQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no linkTransitiveClosureQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from link_transitive_closure")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for link_transitive_closure")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LinkTransitiveClosureSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), linkTransitiveClosurePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"link_transitive_closure\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, linkTransitiveClosurePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from linkTransitiveClosure slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for link_transitive_closure")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *LinkTransitiveClosure) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindLinkTransitiveClosure(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LinkTransitiveClosureSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := LinkTransitiveClosureSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), linkTransitiveClosurePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"link_transitive_closure\".* FROM \"link_transitive_closure\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, linkTransitiveClosurePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in LinkTransitiveClosureSlice")
	}

	*o = slice

	return nil
}

// LinkTransitiveClosureExists checks if the LinkTransitiveClosure row exists.
func LinkTransitiveClosureExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"link_transitive_closure\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if link_transitive_closure exists")
	}

	return exists, nil
}
