version: '3'
volumes:
  clientmodules:
services:
  redis:
    image: redis:5-alpine
    expose:
      - "6379"

  cron:
    build:
      context: .
      dockerfile: k8s/docker/cron/Dockerfile
    image: emwalker/digraph-cron:latest
    env_file:
    - .env.docker.local
    extra_hosts:
    - "database:172.17.0.1"

  api:
    build:
      context: .
      dockerfile: k8s/docker/api/Dockerfile
    image: emwalker/digraph-api:latest
    expose:
      - "8080"
    env_file:
    - .env.docker.local
    extra_hosts:
    - "database:172.17.0.1"
    links:
      - redis
    depends_on:
      - redis

  client:
    image: emwalker/digraph-node:latest
    build:
      context: client
    ports:
      - "3000:3000"
    env_file:
    - .env.docker.local
    depends_on:
      - api
      - redis
    links:
      - api
      - redis
    volumes:
      - clientmodules:/app/client_modules
