version: '3'
volumes:
  nodemodules:
services:
  redis:
    image: redis:5-alpine
    expose:
      - "6379"

  cron:
    build:
      context: .
      dockerfile: k8s/docker/cron/Dockerfile
    image: emwalker/digraph-cron
    env_file:
    - .env.docker.local
    extra_hosts:
    - "database:172.17.0.1"

  api:
    build:
      context: .
      dockerfile: k8s/docker/frontend/Dockerfile
    image: emwalker/digraph-api
    expose:
      - "8080"
    env_file:
    - .env.docker.local
    extra_hosts:
    - "database:172.17.0.1"
    links:
      - redis
    depends_on:
      - redis

  node:
    image: emwalker/digraph-node
    build:
      context: .
      dockerfile: k8s/docker/node/Dockerfile
    ports:
      - "3001:3001"
    env_file:
    - .env.docker.local
    depends_on:
      - api
      - redis
    links:
      - api
      - redis
    volumes:
      - nodemodules:/app/node_modules
