// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DeletedUsers           string
	GithubAccounts         string
	GoogleAccounts         string
	LinkTopics             string
	LinkTransitiveClosure  string
	Links                  string
	OrganizationMembers    string
	Organizations          string
	Repositories           string
	SchemaMigrations       string
	Sessions               string
	Timeranges             string
	TopicTopics            string
	TopicTransitiveClosure string
	Topics                 string
	UserLinkReviews        string
	UserLinkTopics         string
	UserLinks              string
	Users                  string
}{
	DeletedUsers:           "deleted_users",
	GithubAccounts:         "github_accounts",
	GoogleAccounts:         "google_accounts",
	LinkTopics:             "link_topics",
	LinkTransitiveClosure:  "link_transitive_closure",
	Links:                  "links",
	OrganizationMembers:    "organization_members",
	Organizations:          "organizations",
	Repositories:           "repositories",
	SchemaMigrations:       "schema_migrations",
	Sessions:               "sessions",
	Timeranges:             "timeranges",
	TopicTopics:            "topic_topics",
	TopicTransitiveClosure: "topic_transitive_closure",
	Topics:                 "topics",
	UserLinkReviews:        "user_link_reviews",
	UserLinkTopics:         "user_link_topics",
	UserLinks:              "user_links",
	Users:                  "users",
}
