namespace: digraph-prod

bases:
  - ../../../base/digraph

resources:
  - digraph-cron.yaml
  - digraph-frontend.yaml
  - digraph-ingress.yaml

secretGenerator:
  - name: postgres-secrets
    envs:
      - .env.postgres
  - name: digraph-secrets
    envs:
      - .env.digraph

images:
  - name: emwalker/digraph-api
    newTag: v377
  - name: emwalker/digraph-cron
    newTag: v377
  - name: emwalker/digraph-node
    newTag: v377
