#!/bin/bash

podname=$(
  kubectl get pods -n digraph-next -l app=digraph -l \
    tier=frontend --no-headers -o custom-columns=":metadata.name"
)
timestamp=$(date +"%Y%m%d")

echo "packing repo files ..."
kubectl -n digraph-next exec -it $podname -- /tmp/container-pack-data

echo "saving a snapshot of the database ..."
kubectl -n digraph-next exec -it $podname -- /tmp/container-save-db-snapshot

echo "creating a tar file of the repos ..."
kubectl -n digraph-next exec -it $podname \
  -- tar -zcf /var/lib/digraph/backups/latest.tar.gz -C /var/lib/digraph digraph-data/

archive=/var/lib/digraph/backups/latest.tar.gz

echo "copying $archive from $podname to ./data/ directory ..."
kubectl cp --retries=-1 -n digraph-next $podname:$archive \
  data/${timestamp}-production-backup.tar.gz
