#!/bin/bash
set -euf -o pipefail

if [ ! -f data/production-backup.dump ]; then
  echo >&2 data/production-backup.dump not found. You must run make save-production first
  exit 1
fi

dropdb digraph_production >/dev/null 2>&1 || true
createdb digraph_production
psql digraph_production < data/production-backup.dump
