#!/bin/bash

database=digraph_dev
fixtures=digraph_fixtures

echo "Copying ${database} over to ${fixtures}"
psql $database <<SQL
drop database if exists digraph_fixtures;
create database digraph_fixtures with template digraph_dev owner postgres;
SQL

echo "Deleting all but one person's data"
psql $fixtures <<SQL
delete from sessions;
delete from users where not system and id <> '461c87c8-fb8f-11e8-9cbc-afde6c54d881';
delete from organizations where login not in ('wiki', 'emwalker');
delete from links where repository_id = '34a020d6-fc1b-11e8-85cd-bbcf3ebdfe13';
delete from topics where repository_id = '34a020d6-fc1b-11e8-85cd-bbcf3ebdfe13' and not root;
delete from daily_snapshot;
delete from topic_transitive_closure;
delete from link_transitive_closure;
delete from github_accounts where username not in ('emwalker');
delete from google_accounts;
SQL

echo ""
count=$(psql digraph_fixtures -t -c "select count(*) from users")
echo "${count//[[:space:]]/} users"

count=$(psql digraph_fixtures -t -c "select count(*) from repositories")
echo "${count//[[:space:]]/} repositories"

count=$(psql digraph_fixtures -t -c "select count(*) from organizations")
echo "${count//[[:space:]]/} organizations"

count=$(psql digraph_fixtures -t -c "select count(*) from sessions")
echo "${count//[[:space:]]/} sessions"

count=$(psql digraph_fixtures -t -c "select count(distinct user_id) from user_links")
echo "${count//[[:space:]]/} user links"

count=$(psql digraph_fixtures -t -c "select count(*) from links")
echo "${count//[[:space:]]/} links"

count=$(psql digraph_fixtures -t -c "select count(*) from topics")
echo "${count//[[:space:]]/} topics"

count=$(psql digraph_fixtures -t -c "select count(*) from topic_transitive_closure")
echo "${count//[[:space:]]/} topic_transitive_closure"

count=$(psql digraph_fixtures -t -c "select count(*) from link_transitive_closure")
echo "${count//[[:space:]]/} link_transitive_closure"

count=$(psql digraph_fixtures -t -c "select count(*) from daily_snapshot")
echo "${count//[[:space:]]/} snapshots"

count=$(psql digraph_fixtures -t -c "select count(*) from github_accounts")
echo "${count//[[:space:]]/} GitHub accounts"

count=$(psql digraph_fixtures -t -c "select count(*) from google_accounts")
echo "${count//[[:space:]]/} Google accounts"

echo "Saving fixtures.sql"
pg_dump digraph_fixtures > data/fixtures.sql
