#!/bin/bash

set -euf -o pipefail

database=digraph_production
fixtures=digraph_fixtures

echo "Copying ${database} over to ${fixtures}"
psql $database <<SQL
drop database if exists digraph_fixtures;
create database digraph_fixtures with template digraph_production owner postgres;
SQL

echo "Deleting all but one person's data"
psql $fixtures <<SQL
delete from sessions;
delete from users where not system and id <> '461c87c8-fb8f-11e8-9cbc-afde6c54d881';
delete from organizations where login not in ('wiki', 'emwalker');
delete from daily_snapshot;
delete from github_accounts where username not in ('emwalker');
delete from google_accounts;
SQL

echo ""
count=$(psql $fixtures -t -c "select count(*) from users")
echo "${count//[[:space:]]/} users"

count=$(psql $fixtures -t -c "select count(*) from repositories")
echo "${count//[[:space:]]/} repositories"

count=$(psql $fixtures -t -c "select count(*) from organizations")
echo "${count//[[:space:]]/} organizations"

count=$(psql $fixtures -t -c "select count(*) from sessions")
echo "${count//[[:space:]]/} sessions"

count=$(psql $fixtures -t -c "select count(*) from daily_snapshot")
echo "${count//[[:space:]]/} snapshots"

count=$(psql $fixtures -t -c "select count(*) from github_accounts")
echo "${count//[[:space:]]/} GitHub accounts"

count=$(psql $fixtures -t -c "select count(*) from google_accounts")
echo "${count//[[:space:]]/} Google accounts"

echo "Saving fixtures.sql"
pg_dump $fixtures > data/fixtures.sql
