#!/bin/bash
set -euf -o pipefail

if [ "$DIGRAPH_CONNECTION" == "" ]; then
  echo >&2 "DIGRAPH_CONNECTION must be set"
  exit 1
fi

pg_dump "$DIGRAPH_CONNECTION" --exclude-table-data '*transitive_closure*'
