resources:
  - postgresql.yaml
  - redis.yaml
  - digraph-cron.yaml
  - digraph-frontend.yaml

secretGenerator:
  - name: postgres-secrets
    envs:
      - .env.postgres
  - name: digraph-secrets
    envs:
      - .env.digraph
