---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: take-snapshot
spec:
  # Every 12 hours
  schedule: "0 */12 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: emwalker/digraph-cron:v362
            envFrom:
            - secretRef:
                name: digraph-secrets
          restartPolicy: Never
