---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: digraph-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: digraph-frontend
spec:
  ports:
    - name: digraph-frontend-http
      port: 80
      protocol: TCP
      targetPort: 3000
    - name: digraph-frontend-https
      port: 443
      protocol: TCP
      targetPort: 3000
  selector:
    app: digraph
    tier: frontend
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: digraph
    tier: frontend
  name: digraph-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digraph
      tier: frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: digraph
        tier: frontend
    spec:
      restartPolicy: Always
      containers:
        - name: api
          envFrom:
            - secretRef:
                name: digraph-secrets
          image: emwalker/digraph-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          # resources:
          #   requests:
          #     memory: 100Mi
          #   limits:
          #     memory: 600Mi
          volumeMounts:
            - mountPath: /var/lib/digraph
              name: digraph-data
        - name: node
          envFrom:
            - secretRef:
                name: digraph-secrets
          image: emwalker/digraph-node:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          resources:
            requests:
              memory: 150Mi
            limits:
              memory: 400Mi
      volumes:
        - name: digraph-data
          persistentVolumeClaim:
            claimName: digraph-data
