namespace: digraph-next

bases:
  - ../../../base/digraph

resources:
  - digraph-frontend.yaml
  - digraph-ingress.yaml

secretGenerator:
  - name: postgres-secrets
    envs:
      - .env.postgres
  - name: digraph-secrets
    envs:
      - .env.digraph

images:
  - name: emwalker/digraph-api
    newTag: v1.0.6
  - name: emwalker/digraph-node
    newTag: v1.0.6
