namespace: digraph-prod

resources:
  - ../../../base/digraph
  - digraph.yaml
  - digraph-ingress.yaml

secretGenerator:
  - name: postgres-secrets
    envs:
      - .env.postgres
  - name: digraph-secrets
    envs:
      - .env.digraph

images:
  - name: emwalker/digraph-api:latest
    newTag: v1.1.16
  - name: emwalker/digraph-node:latest
    newTag: v1.1.16
  - name: emwalker/digraph-node:next
    newTag: v1.2.25
