---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digraph-frontend
spec:
  template:
    spec:
      containers:
        - name: api
          imagePullPolicy: Never
        - name: node
          imagePullPolicy: Never
