---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: digraph-take-snapshot
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            imagePullPolicy: Never
