// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Links            string
	Organizations    string
	SchemaMigrations string
	Topics           string
	TopicsLinks      string
	TopicsTopics     string
	Users            string
}{
	Links:            "links",
	Organizations:    "organizations",
	SchemaMigrations: "schema_migrations",
	Topics:           "topics",
	TopicsLinks:      "topics_links",
	TopicsTopics:     "topics_topics",
	Users:            "users",
}
